first_tuple = (1,3,4,5,3,6,7,8,9,10,11)

second_tuple = (12,13,14,15,16,17,18,19,20,21,22)
# print(type(first_tuple))
# print(first_tuple.count(3))
# print(first_tuple.index(3))
# print(first_tuple.__add__(second_tuple))
# print(first_tuple.__contains__(3))
# print(first_tuple.__eq__(second_tuple))
# print(first_tuple.index(3))
# print(first_tuple.__len__())   
# print(first_tuple.__mul__(3)) 
print(first_tuple.__getitem__(2))
print(first_tuple.__getstate__)