[project]
name = "intro-to-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
scripts = [
    
]
[project.scripts]
hello-world = "scripts.hello-world:main"
