[project]
name = "first-uv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.2.3",
    "streamlit>=1.42.2",
]
[project.scripts]
running = "main:main"
